# Generated by Django 5.1.2 on 2024-12-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table='user',
        ),
    ]
