# Generated by Django 5.1.2 on 2024-12-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_donor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table='pengguna',
        ),
    ]
