# Generated by Django 5.1.2 on 2024-12-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_jadwaldonor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jadwaldonor',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='jadwaldonor',
            table='app1_jadwaldonor',
        ),
    ]
