# Generated by Django 5.1.2 on 2024-12-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_jadwaldonor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jadwaldonor',
            table='jadwaldonor',
        ),
    ]
