# Generated by Django 5.1.2 on 2024-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_jadwaldonor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaa', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('notelp', models.CharField(max_length=15)),
                ('tanggal', models.DateField()),
            ],
            options={
                'db_table': 'petugas',
            },
        ),
    ]
